- name: Copy Traefik config files
  tags: dep
  copy:
    src: traefik-data
    dest: /home/ubuntu
    owner: "{{ user }}"
    group: "{{ user }}" 
    mode: 0600
    directory_mode: yes

- name: Deploy Traefik
  tags: dep
  community.docker.docker_container:
    name: traefik
    image: "traefik:latest"
    networks:
      - name: "{{ network_name }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik:/etc/traefik
      - /home/ubuntu/traefik-data/traefik.yml:/traefik.yml:ro
      - /home/ubuntu/traefik-data/acme.json:/acme.json
      - /home/ubuntu/traefik-data/configurations:/configurations
      - /home/ubuntu/traefik-data/ebusinesscards.newmurabba.com.csr:/ebusinesscards.newmurabba.com.csr
      - /home/ubuntu/traefik-data/ebusinesscards.newmurabba.com.key:/ebusinesscards.newmurabba.com.key
      - /home/ubuntu/traefik-data/ebusinesscards.newmurabba.com.pem:/ebusinesscards.newmurabba.com.pem
    labels:
      traefik.enable: "true"
      traefik.docker.network: "{{ network_name }}"
      traefik.http.routers.traefik-secure.entrypoints: "websecure"
      traefik.http.routers.traefik-secure.rule: "{{ TRAEFIK_INGRESS_URL }}"
      traefik.http.routers.traefik-secure.middlewares: "user-auth@file"
      traefik.http.routers.traefik-secure.service: "api@internal"
      com.centurylinklabs.watchtower.enable: "false"
    restart_policy: unless-stopped
