---
- name: Install required system packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
    update_cache: yes

- name: Add Docker repository
  command: >
    yum-config-manager
    --add-repo
    https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to Docker group (optional)
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_user_id != 'root'

- name: Verify Docker installation
  command: docker --version
  register: docker_version

- name: Display Docker version
  debug:
    msg: "Docker version installed: {{ docker_version.stdout }}"


- name: install python package manager
  package:
    name: python3-pip

- name: install python sdk
  pip:
    name:
      - docker
