---
- hosts: all
  become: yes
  tasks:
    - name: update docker containers
      tags: app
      community.docker.docker_container:
        name: watchtower
        image: "containrrr/watchtower"
        command: --run-once
        networks:
          - name: spf
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /root/.docker/config.json:/config.json
        env:
          WATCHTOWER_LABEL_ENABLE: "true"
          WATCHTOWER_RUN_ONCE: "true"
        auto_remove: true
