name: APIs docker image build & push

on:
  push:
    branches: ["main"]
    paths:
      - "Api/**"
      - ".github/workflows/api-docker-image.yml"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.0
        with:
          context: Api
          push: true
          tags: hazmi0a/ebusinesscard:v${{ steps.meta.outputs.tags }}