FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 8080
EXPOSE 443
ENV ASPNETCORE_HTTP_PORTS=80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["QRCodePOC.csproj", "./"]
RUN dotnet restore "QRCodePOC.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "QRCodePOC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "QRCodePOC.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "QRCodePOC.dll"]